#!/bin/bash

. /var/www/html/myprivate
tail -F /var/log/nat/nat.log | grep --line-buffered "IN=ens224 OUT=ens192" | while read -r pp; do
  tt=`echo $pp | cut -d' ' -f1`
  if (( $EPOCHSECONDS-$tt <= 5 )); then
    ipsrc=`echo $pp | cut -d' ' -f10`
    ipdst=`echo $pp | cut -d' ' -f11`
    if [[ "$ipdst" != "DST=8.8.8.8" ]]; then
      echo "$tt ${ipsrc:4} ${ipdst:4}" >> /var/www/html/nat
    fi
  fi
done
